/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author giaaa
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Data_Peminjam extends javax.swing.JFrame {

    /**
     * Creates new form Data_Peminjam
     */
    public Data_Peminjam() {
        initComponents();
        tampildata(); //memanggil fungsi menampilkan data
        bersih(); //memanggil fungsi membersihkan text field
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        eNis = new javax.swing.JTextField();
        eNama = new javax.swing.JTextField();
        eKd = new javax.swing.JTextField();
        eJudul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjam = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        eCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEMINJAMAN BUKU SMKN 4 BOGOR");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIS :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KD BUKU :");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUDUL BUKU :");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TANGGAL PINJAM :");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TANGGAL KEMBALI :");

        tabelPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelPeminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjam);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eNis, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(eNama)
                                .addComponent(eKd)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(eKd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(eJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel4.getAccessibleContext().setAccessibleName("KODE BUKU :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    // Ambil nilai dari JTextField
String nis = eNis.getText();
String nama = eNama.getText();
String kode = eKd.getText();
String judul = eJudul.getText();

// Format tanggal yang benar
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

// Ambil tanggal dari jDateChooser dan format sesuai dengan yang dibutuhkan
String tanggalPinjam = sdf.format(jDateChooser1.getDate());
String tanggalKembali = sdf.format(jDateChooser2.getDate());

if (nis.isEmpty() || nama.isEmpty() || kode.isEmpty() || judul.isEmpty() || tanggalPinjam.isEmpty() || tanggalKembali.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Isi semua data!");
    return;
}

try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3310/java_perpustakaan", "root", "");
    String sql = "INSERT INTO data_peminjam (nis, nama, kd_buku, judul_buku, tanggal_pinjam, tanggal_kembali) VALUES (?, ?, ?, ?, ?, ?)";
    PreparedStatement pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, nis);
    pstmt.setString(2, nama);
    pstmt.setString(3, kode);
    pstmt.setString(4, judul);
    pstmt.setString(5, tanggalPinjam);
    pstmt.setString(6, tanggalKembali);
    pstmt.executeUpdate();
    
    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
    tampildata();
    bersih();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
}
    }//GEN-LAST:event_simpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    String nis = eNis.getText();
    String nama = eNama.getText();
    String kode = eKd.getText();
    String judul = eJudul.getText();
    String tanggalPinjam = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
    String tanggalKembali = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3310/java_perpustakaan", "root", "");
        Statement stmt = conn.createStatement();
        String sql = "UPDATE data_peminjam SET nama = '" + nama + "', kd_buku = '" + kode + "', judul_buku = '" + judul + "', tanggal_pinjam = '" + tanggalPinjam + "', tanggal_kembali = '" + tanggalKembali + "' WHERE nis = '" + nis + "'";
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        tampildata();
        bersih();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                           
    String nis = eNis.getText();

    // Cek apakah NIS kosong
    if (nis.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Masukkan NIS yang ingin dihapus!");
        return;
    }

    // Tampilkan dialog konfirmasi sebelum menghapus
    int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data dengan NIS: " + nis + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih 'Yes'
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3310/java_perpustakaan", "root", "");
            String sql = "DELETE FROM data_peminjam WHERE nis = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nis);
            int deletedRows = pstmt.executeUpdate();

            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
            }

            // Refresh data di tabel dan bersihkan input
            tampildata();
            bersih();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    } else {
        // Jika pengguna memilih 'No'
        JOptionPane.showMessageDialog(null, "Penghapusan dibatalkan.");
    }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String cari = eCari.getText();
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIS");
    model.addColumn("Nama");
    model.addColumn("Kode Buku");
    model.addColumn("Judul Buku");
    model.addColumn("Tanggal Pinjam");
    model.addColumn("Tanggal Kembali");

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3310/java_perpustakaan", "root", "");
        Statement stmt = conn.createStatement();
        String sql = "SELECT * FROM data_peminjam WHERE nama LIKE '%" + cari + "%' " +
                     "OR kd_buku LIKE '%" + cari + "%' " +
                     "OR judul_buku LIKE '%" + cari + "%' " +
                     "OR tanggal_pinjam LIKE '%" + cari + "%' " +
                     "OR tanggal_kembali LIKE '%" + cari + "%'";
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nis"),       // Nama kolom di database
                rs.getString("nama"),
                rs.getString("kd_buku"),
                rs.getString("judul_buku"),
                rs.getString("tanggal_pinjam"),
                rs.getString("tanggal_kembali")
            });
        }

        tabelPeminjam.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelPeminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamMouseClicked
        // TODO add your handling code here:
        int row = tabelPeminjam.getSelectedRow();
    if (row != -1) {
        eNis.setText(tabelPeminjam.getValueAt(row, 0).toString());
        eNama.setText(tabelPeminjam.getValueAt(row, 1).toString());
        eKd.setText(tabelPeminjam.getValueAt(row, 2).toString());
        eJudul.setText(tabelPeminjam.getValueAt(row, 3).toString());
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(tabelPeminjam.getValueAt(row, 4).toString());
        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(tabelPeminjam.getValueAt(row, 5).toString());
    }
    }//GEN-LAST:event_tabelPeminjamMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    this.dispose(); // Menutup jendela saat ini
    Form_Utama formUtama = new Form_Utama(); // Membuat instance baru dari Form_Utama
    formUtama.setVisible(true); // Menampilkan Form_Utama
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Peminjam().setVisible(true);
            }
        });
    }
    
    private void tampildata() {
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("NIS");
    tbl.addColumn("Nama");
    tbl.addColumn("Kode Buku");
    tbl.addColumn("Judul Buku");
    tbl.addColumn("Tanggal Pinjam");
    tbl.addColumn("Tanggal Kembali");
    tabelPeminjam.setModel(tbl);

    try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3310/java_perpustakaan", "root", "");
        Statement statement = connection.createStatement();
        ResultSet res = statement.executeQuery("SELECT * FROM data_peminjam ORDER BY nama ASC");

        while (res.next()) {
            tbl.addRow(new Object[]{
                res.getString("nis"),
                res.getString("nama"),
                res.getString("kd_buku"),
                res.getString("judul_buku"),
                res.getDate("tanggal_pinjam"), // Tampilkan tanggal pinjam
                res.getDate("tanggal_kembali") // Tampilkan tanggal kembali
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        e.printStackTrace();
    }
}

    
    private void bersih() {
    eNis.setText("");
    eNama.setText("");
    eKd.setText("");
    eJudul.setText("");
    ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
    ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eCari;
    private javax.swing.JTextField eJudul;
    private javax.swing.JTextField eKd;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNis;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelPeminjam;
    // End of variables declaration//GEN-END:variables
}
