/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author giaaa
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Data_Anggota extends javax.swing.JFrame {

    /**
     * Creates new form Data_Pengunjung
     */
    public Data_Anggota() {
        initComponents();
        tampildata(); //memanggil fungsi menampilkan data
        bersih(); //memanggil fungsi membersihkan text field
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLaki = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eNis = new javax.swing.JTextField();
        eNama = new javax.swing.JTextField();
        eTelepon = new javax.swing.JTextField();
        cbJurusan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        eCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA ANGGOTA PERPUSTAKAAN SMKN 4 BOGOR");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIS :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS KELAMIN");

        bgLaki.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki-laki");

        bgLaki.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELEPON");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JURUSAN");

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPLG", "TJKT", "TPFL", "TKRO" }));

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        jButton1.setText("tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbLaki)
                                .addGap(27, 27, 27)
                                .addComponent(rbPerempuan))
                            .addComponent(eNis, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(eNama)
                            .addComponent(eTelepon)
                            .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(575, 575, 575)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(43, 43, 43)
                                .addComponent(jButton2)
                                .addGap(27, 27, 27)
                                .addComponent(jButton4)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbLaki)
                            .addComponent(rbPerempuan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(eTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nis = eNis.getText();
        String nama = eNama.getText();
        String jenis_kelamin = rbLaki.isSelected() ? "Laki-Laki" : "Perempuan";
        String telepon = eTelepon.getText();
        String jurusan = (String) cbJurusan.getSelectedItem();

        // Validasi: Pastikan semua field diisi
        if (nis.isEmpty() || nama.isEmpty() || (!rbLaki.isSelected() && !rbPerempuan.isSelected()) || jurusan == null || telepon == null || telepon.isEmpty() || jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi lengkap datanya!");
        } else {
            try {
                Connection conn = Koneksi_db.getConnection();
                String sql = "INSERT INTO data_anggota (nis, nama, jenis_kelamin, telepon,jurusan) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nis);
                pstmt.setString(2, nama);
                pstmt.setString(3, jenis_kelamin);
                pstmt.setString(4, telepon);
                pstmt.setString(5, jurusan);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                tampildata(); // Refresh tabel
                bersih(); // Bersihkan form
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tabelAnggota.getSelectedRow();
        if (row >= 0) { // Memeriksa jika ada baris yang dipilih
            String nim = (String) tabelAnggota.getValueAt(row, 0);
            String nama = eNama.getText();
            String telepon = eTelepon.getText();
            String jurusan = (String) cbJurusan.getSelectedItem();

            // Pastikan salah satu radio button dipilih
            String jenis_kelamin;
            if (rbLaki.isSelected()) {
                jenis_kelamin = "Laki-Laki";
            } else if (rbPerempuan.isSelected()) {
                jenis_kelamin = "Perempuan";
            } else {
                JOptionPane.showMessageDialog(null, "Pilih jenis kelamin");
                return; // Hentikan proses jika jenis kelamin belum dipilih
            }

            try {
                Connection conn = Koneksi_db.getConnection();
                String sql = "UPDATE data_anggota SET nama = ?, jenis_kelamin = ?, telepon = ?, jurusan = ? WHERE nis = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nama);
                pstmt.setString(2, jenis_kelamin);
                pstmt.setString(3, telepon);
                pstmt.setString(4, jurusan);
                pstmt.setString(5, nim);   // Nim sebagai parameter terakhir

                pstmt.executeUpdate();

                // Menampilkan data terbaru di tabel
                tampildata();
                bersih();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal mengupdate data: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diedit");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = tabelAnggota.getSelectedRow();
        if (row >= 0) { // Memastikan ada baris yang dipilih
            String nis = (String) tabelAnggota.getValueAt(row, 0);

            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data dengan NIS: " + nis + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = Koneksi_db.getConnection();
                    String sql = "DELETE FROM data_anggota WHERE nis = ?";
                    PreparedStatement pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, nis);

                    pstmt.executeUpdate();

                    // Menampilkan data terbaru di tabel
                    tampildata();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
        String cari = eCari.getText(); // Menggunakan nama variabel pencarian yang benar
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("nis");
        tbl.addColumn("nama");
        tbl.addColumn("jenis_kelamin");
        tbl.addColumn("telepon");
        tbl.addColumn("jurusan");
        
        tabelAnggota.setModel(tbl);

        try {
            Statement statement = (Statement) Koneksi_db.getConnection().createStatement();
            ResultSet res = statement.executeQuery(
                    "SELECT * FROM data_anggota WHERE nis LIKE '%" + cari + "%' "
                    + "OR nama LIKE '%" + cari + "%' "
                    + "OR jenis_kelamin LIKE '%" + cari + "%' "
                    + "OR telepon LIKE '%" + cari + "%' "
                    + "OR jurusan LIKE '%" + cari + "%' "
                    
            );

            // Bersihkan tabel sebelumnya
            tbl.setRowCount(0);

            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("nis"),
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("telepon"),
                    res.getString("jurusan"),
                   
                });
            }

            if (tbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
            }

            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal mencari data: " + e.getMessage());
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        int row = tabelAnggota.getSelectedRow();
        if (row >= 0) { // Memastikan ada baris yang dipilih
            eNis.setText((String) tabelAnggota.getValueAt(row, 0));
            eNama.setText((String) tabelAnggota.getValueAt(row, 1));
            // Menetapkan status JRadioButton berdasarkan nilai dari tabel
            String jenisKelamin = (String) tabelAnggota.getValueAt(row, 2);
            if ("Laki-Laki".equals(jenisKelamin)) {
                rbLaki.setSelected(true);
                rbPerempuan.setSelected(false);
            } else if ("Perempuan".equals(jenisKelamin)) {
                rbLaki.setSelected(false);
                rbPerempuan.setSelected(true);
            } else {
                // Jika nilai tidak sesuai, pastikan tidak ada radio button yang dipilih
                rbLaki.setSelected(false);
                rbPerempuan.setSelected(false);
            }
            eTelepon.setText((String) tabelAnggota.getValueAt(row, 3));
            cbJurusan.setSelectedItem((String) tabelAnggota.getValueAt(row, 4));
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diedit");
        }
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Anggota().setVisible(true);
            }
        });
    }

    public void bersih() {
        eNis.setText("");
        eNama.setText("");
        eCari.setText("");
        cbJurusan.setSelectedIndex(0);
        rbLaki.setSelected(false);
    }

    public void tampildata() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIS");
        tbl.addColumn("Nama");
        tbl.addColumn("jenis_kelamin");
        tbl.addColumn("telepon");
        tbl.addColumn("jurusan");
        tabelAnggota.setModel(tbl);
        try {
            Connection connection = Koneksi_db.getConnection();
            if (connection != null) {
                System.out.println("Koneksi berhasil!");
            } else {
                System.out.println("Koneksi gagal!");
            }
            Statement statement = connection.createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM data_anggota ORDER BY nama ASC");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("Nis"),
                    res.getString("Nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("telepon"),
                    res.getString("jurusan"),});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Salah: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLaki;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JTextField eCari;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNis;
    private javax.swing.JTextField eTelepon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tabelAnggota;
    // End of variables declaration//GEN-END:variables
}
