/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author giaaa
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class Form_Register extends javax.swing.JFrame {

    /**
     * Creates new form Form_Register
     */
    public Form_Register() {
        initComponents();
        Koneksi_db.openConnection(); // Buka koneksi ke database
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        eUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbJurusan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        eNis = new javax.swing.JTextField();
        ePassword = new javax.swing.JPasswordField();
        eKonfir = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("HALAMAN REGISTER DATA ANGGOTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setText("Nama : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel5.setText("Username :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel6.setText("Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel7.setText("Konfirmasi Password :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));
        getContentPane().add(eNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 260, -1));
        getContentPane().add(eUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 260, -1));

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 250, -1));

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPLG", "TJKT", "TPFL", "TKRO" }));
        getContentPane().add(cbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        jLabel8.setText("Nis :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        getContentPane().add(eNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 260, -1));
        getContentPane().add(ePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 260, -1));
        getContentPane().add(eKonfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 240, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("WEBSITE PERPUSTAKAAN SMKN 4 BOGOR");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // Validasi password dan konfirmasi password
        String password = new String(ePassword.getPassword());
        String konfirpassword = new String(eKonfir.getPassword());

        if (!password.equals(konfirpassword)) {
            JOptionPane.showMessageDialog(null, "Password dan Konfirmasi Password tidak sama!");
            return;
        }

        try {
        // Insert data ke tbregister
        String sqlRegister = "INSERT INTO tbregister (nis, nama, username, jurusan, password) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement psRegister = Koneksi_db.getConnection().prepareStatement(sqlRegister);

        psRegister.setString(1, eNis.getText());        // NIS
        psRegister.setString(2, eNama.getText());       // Nama
        psRegister.setString(3, eUser.getText());       // Username
        psRegister.setString(4, cbJurusan.getSelectedItem().toString()); // Jurusan dari ComboBox
        psRegister.setString(5, password);              // Password yang sudah divalidasi

        psRegister.executeUpdate();  // Menyimpan data ke database tbregister

        // Insert data ke tblogin
        String sqlLogin = "INSERT INTO tblogin (username, password) VALUES (?, ?)";
        PreparedStatement psLogin = Koneksi_db.getConnection().prepareStatement(sqlLogin);

        psLogin.setString(1, eUser.getText());   // Username
        psLogin.setString(2, password);          // Password yang sudah divalidasi

        psLogin.executeUpdate();  // Menyimpan data ke database tblogin

        JOptionPane.showMessageDialog(null, "Registrasi berhasil!");

        // Alihkan ke halaman login setelah registrasi sukses
        From_Login loginForm = new From_Login();
        loginForm.setVisible(true);
        this.dispose(); // Menutup halaman register
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JPasswordField eKonfir;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNis;
    private javax.swing.JPasswordField ePassword;
    private javax.swing.JTextField eUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
